# pv-bot-A.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-pv-bot-a
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/openclaw/bot-a

---
# pv-bot-B.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-pv-bot-b
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/openclaw/bot-b

